In [61]:
import numpy as np
possdm1 = [[16420,26260],[17120, 28480],[18600,31760],[12060,28640],[24620, 44740],[23780, 41560],[22980, 39580]]
possd = [[15760, 26500],[16420, 28780],[17940,32040],[11380,29000],[24300,44820],[23440, 41660],[22560,39720]]
listeA, listeB = possdm1,possd
H = np.dot(
    np.transpose(np.array(listeA) - np.mean(listeA, axis=0)),
    np.array(listeB) - np.mean(listeB, axis=0),
)
U, S, V = np.linalg.svd(H)
R = np.dot(V, np.transpose(U))
t = np.mean(listeB, axis=0) - np.dot(R, np.mean(listeA, axis=0))
R,t

(array([[ 0.99974618,  0.02252963],
        [-0.02252963,  0.99974618]]),
 array([-1310.81123275,   659.39205642]))

In [74]:
pos = [7820,27200]
np.dot(R,pos)+t

array([ 7120.00987752, 27676.30630299])

In [34]:
mflow = 5.4e-5 #kg.s-1
As = 0.05 #m**2
mflow_area = mflow/As #kg.s-1.m**-2
length_flux = mflow_area * 10**-3

In [35]:
length_flux

1.0799999999999998e-06

In [60]:
import numpy as np
possdm1 = [[15380,30640],[12880,36120],[10620,45020]]
possd = [[15540,30500],[13060,35920],[10620,45020]]
listeA, listeB = possdm1,possd
H = np.dot(
    np.transpose(np.array(listeA) - np.mean(listeA, axis=0)),
    np.array(listeB) - np.mean(listeB, axis=0),
)
U, S, V = np.linalg.svd(H)
R = np.dot(V, np.transpose(U))
t = np.mean(listeB, axis=0) - np.dot(R, np.mean(listeA, axis=0))
R,t

(array([[ 0.99996828, -0.00796539],
        [ 0.00796539,  0.99996828]]),
 array([ 410.53506663, -215.38279608]))

In [68]:
pos = [36220,36040]
np.dot(R,pos)+t

array([36342.31320805, 36111.98043876])